apiVersion: v1
kind: Pod
metadata:
  name: myfirst-pod
  labels:
    app: myfirst-pod
    type: front-end
  annotations:
    on-call: "prod@support.com"
    dependencies: "Python 3.6, Harbor, NodeJS"
spec:
  containers:
  - name: my-container-1
    image: nginx