apiVersion: apps/v1
kind: RelicaSet
metadata:
  name: my-rs
  labels:
    app: my-rs
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: myfirst-pod
      labels:
        app: myfirst-pod
        type: front-end
      annotations:
        on-call: "prod@support.com"
        dependencies: "Python 3.6, Harbor, NodeJS"
    spec:
      containers:
      - name: my-container-1
        image: nginx
  selector:
    matchLabels:
      type: front-end